"""Constants for the modbus_devices integration."""

class Config:
    """Settings constants params."""

    DOMAIN: str = "modbus_devices"
    NAME: str = "Modbus Devices"

    TIME_ZONE: int = 7  # in hours timezone integer

    CONF_MODBUS_MODE: str = "modbus_mode"
    CONF_DEVICE_CLASS: str = "device_class"
    CONF_GATEWAY_MAPPING: str = "gateway_mapping"
    CONF_GATEWAY_ID: str = "gateway_id"
    CONF_GATEWAY_ENTRY_ID: str = "gateway_entry_id"
    CONF_GATEWAY_SELECTION: str = "gateway_selection"
    CONF_DISCOVERED_ADDRESS: str = "discovered_address"
    CONF_MAPPING_SOURCE: str = "mapping_source"
    CONF_ORION_ADDRESS: str = "orion_address"
    CONF_OBJECT_KIND: str = "object_kind"
    CONF_DATA_AREA: str = "data_area"
    CONF_LOCAL_OBJECT_NUMBER: str = "local_object_number"
    CONF_GATEWAY_OBJECT_NUMBER: str = "gateway_object_number"
    CONF_RESOLVED_MODBUS_ADDRESS: str = "resolved_modbus_address"
    CONF_ADD_ANOTHER_OBJECT: str = "add_another_object"
    CONF_ZONE_TYPE: str = "zone_type"
    CONF_PARTITION_NUMBER: str = "partition_number"
    CONF_PARTITION_ID: str = "partition_id"
    CONF_CAPABILITY_KEY: str = "capability_key"
    CONF_DEVICE_VARIANT: str = "device_variant"
    CONF_DEVICE_TOPOLOGY: str = "device_topology"
    CONF_DPLS_BASE_ADDRESS: str = "dpls_base_address"
    CONF_IO_MAPPING: str = "io_mapping"
    CONF_DI_DATA_AREA: str = "di_data_area"
    CONF_DI_BASE_ADDRESS: str = "di_base_address"
    CONF_DI_ADDRESS_STRIDE: str = "di_address_stride"
    CONF_DO_BASE_ADDRESS: str = "do_base_address"
    CONF_DO_ADDRESS_STRIDE: str = "do_address_stride"

    CONF_MANUFACTURER: str = "manufacturer"

    CONF_COM_PORT: str = "com_port"
    CONF_BAUDRATE: str = "baudrate"
    CONF_BYTESIZE: str = "bytesize"
    CONF_PARITY: str = "parity"
    CONF_STOPBITS: str = "stopbits"
    CONF_LOCAL_UDP_PORT: str = "local_udp_port"
    CONF_REMOTE_PORT: str = "remote_port"
    CONF_LOCAL_BIND_ADDRESS: str = "local_bind_address"
    CONF_TIMEOUT: str = "timeout"

    CONF_CONNECT_TO: str = "connect_to"

    MODBUS_TCP: str = "ModBus TCP/IP"
    MODBUS_UDP: str = "ModBus UDP/IP"
    MODBUS_RTU_OVER_UDP: str = "rtu_over_udp"
    MODBUS_SERIAL: str = "SerialPort"
